services:
  tomcat:
    #https://www.baeldung.com/tomcat-catalina_opts-vs-java_opts
    image: tomcat:9
    environment:
      ORACLE_PWD: ${ORACLE_PWD:-oracle#Pwd}
      APEX_PWD: ${APEX_PWD:-apex#Pwd}
    volumes:
      - ./apex:/opt/apex
      - ./02_ords_install.sh /tmp/02_ords_install.sh
    ports:
      - ${TOMCAT_PORT:-18080}:8080
    depends_on:
      - dbora
    restart: "unless-stopped"
  dbora:
    build:
      context: ./dbora
      dockerfile: Dockerfile
    environment:
      ORACLE_PWD: ${ORACLE_PWD:-oracle#Pwd}
      APEX_PWD: ${APEX_PWD:-apex#Pwd}
      APEX_ADMIN_PWD: ${APEX_ADMIN_PWD:-apexadmin#Pwd}
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./apex:/home/oracle/apex
      - ./01_apex_install.sh:/home/oracle/01_apex_install.sh
    ports:
      - ${ORACLE_PORT:-11521}:1521
    restart: "unless-stopped"
